baseURL = "https://imogenliu.com/"
languageCode = "en-us"
title = "Imogen T. Liu"
theme = "ananke"
themesDir = "themes"
enableRobotsTXT = true
disableKinds = ["taxonomy"]

[pagination]
pagerSize = 10

[params]
  description = "Assistant Professor of International Political Economy at Vrije Universiteit Amsterdam"
  author = "Imogen T. Liu"
  mainSections = ["posts"]
  featured_image = "/images/hero-background.jpg"
  background_color_class = "bg-black"
  recent_posts_number = 3
  
  # Add this section to register your custom CSS with Ananke
  [params.ananke]
    custom_css = ["custom.css"]

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
  [[menu.main]]
    name = "Research"
    url = "/research/"
    weight = 3
  [[menu.main]]
    name = "Publications"
    url = "/publications/"
    weight = 4
  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 5

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    lineNos = false
    noClasses = false
  [markup.goldmark]
      unsafe = true
