baseURL = "https://imogenliu.com/"
languageCode = "en-us"
title = "Anonymous"
theme = "hugo-researcher"
themesDir = "themes"
enableRobotsTXT = true
disableKinds = ["taxonomy", "section"]
resourceDir = "public"
publishDir = "public"

[params]
  description = "description..."
  author = "Anonymous"
  mainSections = ["posts"]
  featured_image = "/images/hero-background.jpg"
  background_color_class = "bg-black"
  recent_posts_number = 3
  keywords = ["Political Science", "Political Economy", "Development", "China", "International Relations", "Geopolitics", "Geoeconomics", "China-EU Relations", "Public Finance", "Financial Markets", "Investment", "Infrastructure", "State Capitalism", "Financialization", "Economic Geography"]

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1