baseURL = "https://imogenliu.com/"
languageCode = "en-us"
title = "Imogen T. Liu"
theme = "hugo-researcher"
themesDir = "themes"
enableRobotsTXT = true
disableKinds = ["taxonomy", "section"]
resourceDir = "public"
publishDir = "public"

[pagination]
pagerSize = 10

[params]
  description = "Assistant Professor, Faculty of Social Sciences, Political Science and Public Administration, Vrije Universiteit Amsterdam | Research Associate at Second Cold War Observatory and FINGEO network"
  author = "Imogen T. Liu"
  mainSections = ["posts"]
  featured_image = "/images/hero-background.jpg"
  background_color_class = "bg-black"
  recent_posts_number = 3
  keywords = ["Political Science", "Political Economy", "Development", "China", "International Relations", "Geopolitics", "Geoeconomics", "China-EU Relations", "Public Finance", "Financial Markets", "Investment", "Infrastructure", "State Capitalism", "Financialization", "Economic Geography"]

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
  [[menu.main]]
    name = "Research"
    url = "/research/"
    weight = 3
  [[menu.main]]
    name = "Publications"
    url = "/publications/"
    weight = 4
  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 5

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    lineNos = false
    noClasses = false
  [markup.goldmark]
      unsafe = true

[outputs]
home = ["HTML", "RSS"]

[environments.production]
  buildDrafts = false
  buildFuture = false
  buildExpired = false
